//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace GISRZ.Models
{
	public partial class security
	{
		//public security()
		//{
		//	this.security_roles = new HashSet<security_roles>();
		//}
	
		public int page_id { get; set; }
		public string url { get; set; }
		public string name { get; set; }
		public string description { get; set; }
		public string disabled { get; set; }
		public Nullable<DateTime> disabled_date { get; set; }
		public Nullable<int> disabled_user_id { get; set; }
	
		public virtual ICollection<security_roles> roles { get; set; }
	}
}
