//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;

namespace GISRZ.Models
{
	public partial class user : IUser
	{
		//public user()
		//{
		//	this.roles = new HashSet<role>();
		//}
		public int user_id { get; set; }
		public string network_id { get; set; }
		public Nullable<int> employee_id { get; set; }
		public string first_name { get; set; }
		public string last_name { get; set; }
		public Nullable<DateTime> last_login { get; set; }
		public Nullable<DateTime> last_updated { get; set; }
		public string disabled { get; set; }
		public Nullable<DateTime> disabled_date { get; set; }
		public Nullable<int> disabled_user_id { get; set; }
		public virtual ICollection<user_roles> roles  { get; set; }

		public string UserName
		{
			get { return network_id; }
			set { }
			
		}

		string IUser<string>.Id
		{
			get
			{
				return user_id.ToString(); 
			}
		}

		public string SecurityStamp 
		{
			get { return "xxx" + this.network_id; } set{} }
	}
}
